export const DEFAULT_OPTIONS = [
    { type: 'STATUS', key: 'TODO', label: 'To Do 📝', color: 'bg-gray-100 text-gray-600', sort_order: 1, progress_value: 0 },
    { type: 'STATUS', key: 'IDEA', label: 'Idea / Draft 💡', color: 'bg-yellow-50 text-yellow-600', sort_order: 2, progress_value: 15 },
    { type: 'STATUS', key: 'SCRIPT', label: 'Scripting ✍️', color: 'bg-orange-50 text-orange-600', sort_order: 3, progress_value: 30 },
    { type: 'STATUS', key: 'SHOOTING', label: 'Shooting 🎥', color: 'bg-purple-50 text-purple-600', sort_order: 4, progress_value: 50 },
    { type: 'STATUS', key: 'EDIT_CLIP', label: 'Editing ✂️', color: 'bg-indigo-50 text-indigo-600', sort_order: 5, progress_value: 70 },
    { type: 'STATUS', key: 'FEEDBACK', label: 'Review / Feedback 👀', color: 'bg-pink-50 text-pink-600', sort_order: 6, progress_value: 85 },
    { type: 'STATUS', key: 'APPROVE', label: 'Approved 👍', color: 'bg-emerald-50 text-emerald-600', sort_order: 7, progress_value: 95 },
    { type: 'STATUS', key: 'DONE', label: 'Done ✅', color: 'bg-green-100 text-green-700', sort_order: 8, progress_value: 100 },
    { type: 'TASK_STATUS', key: 'TODO', label: 'To Do (รอทำ) 📥', color: 'bg-gray-100 text-gray-600', sort_order: 1 },
    { type: 'TASK_STATUS', key: 'DOING', label: 'Doing (กำลังทำ) 🔨', color: 'bg-blue-50 text-blue-600', sort_order: 2 },
    { type: 'TASK_STATUS', key: 'WAITING', label: 'Waiting (รอตรวจ/รอผล) ✋', color: 'bg-orange-50 text-orange-600', sort_order: 3 },
    { type: 'TASK_STATUS', key: 'DONE', label: 'Done (เสร็จแล้ว) ✅', color: 'bg-green-100 text-green-700', sort_order: 4 },
    { type: 'FORMAT', key: 'SHORT_FORM', label: 'Short Form (สั้น)', color: 'bg-rose-100 text-rose-700', sort_order: 1 },
    { type: 'FORMAT', key: 'LONG_FORM', label: 'Long Form (ยาว)', color: 'bg-indigo-100 text-indigo-700', sort_order: 2 },
    { type: 'FORMAT', key: 'REELS', label: 'Reels / TikTok', color: 'bg-zinc-100 text-zinc-700', sort_order: 3 },
    { type: 'FORMAT', key: 'PICTURE', label: 'Photo / Album', color: 'bg-teal-100 text-teal-700', sort_order: 4 },
    { type: 'FORMAT', key: 'STORY', label: 'Story', color: 'bg-amber-100 text-amber-700', sort_order: 5 },
    { type: 'PILLAR', key: 'ENTERTAINMENT', label: 'Entertainment 🎬', color: 'bg-purple-100 text-purple-700', sort_order: 1 },
    { type: 'PILLAR', key: 'EDUCATION', label: 'Education 📚', color: 'bg-blue-100 text-blue-700', sort_order: 2 },
    { type: 'PILLAR', key: 'LIFESTYLE', label: 'Lifestyle 🌱', color: 'bg-green-100 text-green-700', sort_order: 3 },
    { type: 'PILLAR', key: 'PROMO', label: 'Promotion 📢', color: 'bg-orange-100 text-orange-700', sort_order: 4 },
    { type: 'PILLAR', key: 'REALTIME', label: 'Realtime / News ⚡', color: 'bg-red-100 text-red-700', sort_order: 5 },
    { type: 'CATEGORY', key: 'VLOG', label: 'Vlog', color: 'bg-gray-100 text-gray-700', sort_order: 1 },
    { type: 'CATEGORY', key: 'REVIEW', label: 'Review', color: 'bg-gray-100 text-gray-700', sort_order: 2 },
    { type: 'CATEGORY', key: 'HOW_TO', label: 'How-to', color: 'bg-gray-100 text-gray-700', sort_order: 3 },
    { type: 'CATEGORY', key: 'INTERVIEW', label: 'Interview', color: 'bg-gray-100 text-gray-700', sort_order: 4 },
    { type: 'POSITION', key: 'CEO', label: 'CEO', color: 'bg-slate-900 text-white', sort_order: 0 },
    { type: 'POSITION', key: 'HR_MANAGER', label: 'HR Manager', color: 'bg-pink-100 text-pink-700', sort_order: 1 },
    { type: 'POSITION', key: 'SENIOR_HR', label: 'Senior HR', color: 'bg-pink-50 text-pink-600', sort_order: 2 },
    { type: 'POSITION', key: 'CREATIVE', label: 'Creative', color: 'bg-yellow-100 text-yellow-700', sort_order: 3 },
    { type: 'POSITION', key: 'EDITOR', label: 'Editor', color: 'bg-blue-100 text-blue-700', sort_order: 4 },
    { type: 'POSITION', key: 'PRODUCTION', label: 'Production', color: 'bg-green-100 text-green-700', sort_order: 5 },
    { type: 'POSITION', key: 'ADMIN', label: 'Admin / Co-ord', color: 'bg-purple-100 text-purple-700', sort_order: 6 },
    { type: 'WORK_CONFIG', key: 'START_TIME', label: '10:00', color: '', sort_order: 1 },
    { type: 'WORK_CONFIG', key: 'END_TIME', label: '19:00', color: '', sort_order: 2 },
    { type: 'WORK_CONFIG', key: 'LATE_BUFFER', label: '15', color: '', sort_order: 3 },
    { type: 'WORK_CONFIG', key: 'MIN_HOURS', label: '9', color: '', sort_order: 4 },
    { type: 'WORK_CONFIG', key: 'OT_THRESHOLD_HOURS', label: '2', color: '', sort_order: 5 },
    { type: 'WORK_CONFIG', key: 'CHECKOUT_PENALTY_TIME', label: '06:00', color: '', sort_order: 6 },
    { type: 'WORK_CONFIG', key: 'DAILY_SUMMARY_DELAY_HOURS', label: '1', color: '', sort_order: 7 },
    { type: 'WORK_CONFIG', key: 'LINE_SUMMARY_DESTINATION', label: '', color: '', sort_order: 8 },
    { type: 'WORK_CONFIG', key: 'HP_PENALTY_EARLY_LEAVE_INTERVAL', label: '10', color: '', sort_order: 9 },
    { type: 'WORK_CONFIG', key: 'HP_PENALTY_EARLY_LEAVE_RATE', label: '1', color: '', sort_order: 10 },
    { type: 'WORK_CONFIG', key: 'ENABLE_ATTENDANCE_RACE', label: 'true', color: '', sort_order: 11, description: 'เปิด-ปิดระบบสนามวิ่งแข่งเช็คอินรายวันสำหรับพนักงาน' },
    { type: 'ATTENDANCE_TYPE', key: 'OFFICE', label: 'เข้าออฟฟิศ', color: 'bg-indigo-600', sort_order: 10 },
    { type: 'ATTENDANCE_TYPE', key: 'ON_TIME', label: 'มาตรงเวลา (On Time)', color: 'bg-emerald-600', sort_order: 15, description: '{"icon": "CheckCircle", "category": "STANDARD"}' },
    { type: 'ATTENDANCE_TYPE', key: 'WFH', label: 'ทำงานที่บ้าน (WFH)', color: 'bg-blue-600', sort_order: 10, description: '{"icon": "Home", "category": "STANDARD"}' },
    { type: 'ATTENDANCE_TYPE', key: 'SITE', label: 'ออกกอง/ข้างนอก', color: 'bg-orange-500', sort_order: 10, description: '{"icon": "MapPin", "category": "STANDARD"}' },
    { type: 'ATTENDANCE_TYPE', key: 'LATE', label: 'มาสาย (Late)', color: 'bg-yellow-500', sort_order: -5, description: '{"icon": "Clock", "category": "STANDARD"}' },
    { type: 'ATTENDANCE_TYPE', key: 'EARLY_LEAVE', label: 'กลับก่อน (Early)', color: 'bg-orange-400', sort_order: -5, description: '{"icon": "LogOut", "category": "STANDARD"}' },
    { type: 'ATTENDANCE_TYPE', key: 'ABSENT', label: 'ขาดงาน (Absent)', color: 'bg-red-500', sort_order: -20, description: '{"icon": "UserX", "category": "STANDARD"}' },
    { type: 'ATTENDANCE_TYPE', key: 'NO_SHOW', label: 'หายเงียบ (No Show)', color: 'bg-red-800', sort_order: -50, description: '{"icon": "Ghost", "category": "STANDARD"}' },
    { type: 'LEAVE_TYPE', key: 'SICK', label: 'ลาป่วย', color: 'bg-red-500', sort_order: 1, description: '{"icon": "HeartPulse", "category": "STANDARD", "defaultQuota": 30, "placeholder": "ระบุอาการป่วย..."}' },
    { type: 'LEAVE_TYPE', key: 'VACATION', label: 'พักร้อน', color: 'bg-blue-500', sort_order: 2, description: '{"icon": "Palmtree", "category": "STANDARD", "defaultQuota": 6, "placeholder": "ระบุแผนการพักผ่อน..."}' },
    { type: 'LEAVE_TYPE', key: 'PERSONAL', label: 'ลากิจ', color: 'bg-purple-500', sort_order: 3, description: '{"icon": "Briefcase", "category": "STANDARD", "defaultQuota": 6, "placeholder": "ระบุธุระที่จำเป็น..."}' },
    { type: 'LEAVE_TYPE', key: 'EMERGENCY', label: 'ลาฉุกเฉิน', color: 'bg-rose-600', sort_order: 4, description: '{"icon": "AlertCircle", "category": "STANDARD", "defaultQuota": 3, "placeholder": "ระบุเหตุฉุกเฉิน..."}' },
    { type: 'LEAVE_TYPE', key: 'WFH', label: 'Work From Home', color: 'bg-blue-600', sort_order: 0, description: '{"icon": "Home", "category": "SPECIAL", "subLabel": "ขออนุญาตทำงานที่บ้าน", "defaultQuota": 100, "placeholder": "เช่น เคลียร์งานตัดต่อที่บ้าน...", "reasonLabel": "รายละเอียดงานที่จะทำ (Task)"}' },
    { type: 'LEAVE_TYPE', key: 'OVERTIME', label: 'ขอทำ OT', color: 'bg-indigo-600', sort_order: 5, description: '{"icon": "Moon", "category": "SPECIAL", "subLabel": "ขอทำงานล่วงเวลา", "defaultQuota": 999, "placeholder": "เช่น เร่งปิดงานลูกค้า Project A...", "reasonLabel": "รายละเอียดงานที่จะทำ (OT Task)"}' },
    { type: 'LEAVE_TYPE', key: 'LATE_ENTRY', label: 'แจ้งเข้าสาย', color: 'bg-amber-500', sort_order: 10, description: '{"icon": "Clock", "category": "CORRECTION", "defaultQuota": 999, "placeholder": "เช่น รถติดหนักมากที่แยก..."}' },
    { type: 'LEAVE_TYPE', key: 'FORGOT_CHECKIN', label: 'ลืมลงเวลาเข้า', color: 'bg-rose-500', sort_order: 11, description: '{"icon": "LogIn", "category": "CORRECTION", "defaultQuota": 999, "placeholder": "เช่น ลืมกดเข้างานเนื่องจากรีบไปประชุม..."}' },
    { type: 'LEAVE_TYPE', key: 'FORGOT_CHECKOUT', label: 'ลืมลงเวลาออก', color: 'bg-orange-500', sort_order: 12, description: '{"icon": "LogOut", "category": "CORRECTION", "defaultQuota": 999, "placeholder": "เช่น ลืมกดออกเนื่องจากรีบไปธุระต่อ..."}' },
    { type: 'LEAVE_TYPE', key: 'FORGOT_BOTH', label: 'ลืมทั้งเข้า-ออก', color: 'bg-red-600', sort_order: 13, description: '{"icon": "History", "category": "CORRECTION", "defaultQuota": 999, "placeholder": "เช่น ลืมกดทั้งเข้าและออกเนื่องจาก..."}' },
    { type: 'LEAVE_TYPE', key: 'UNPAID', label: 'ลาไม่รับค่าจ้าง', color: 'bg-slate-800', sort_order: 20, description: '{"icon": "FileText", "category": "STANDARD", "defaultQuota": 999, "placeholder": "ระบุเหตุผลการลา..."}' },
    { type: 'ATTENDANCE_RULE_KEY', key: 'CORRECTION_REFUND', label: 'คืนค่า HP (แก้เวลาออก)', color: 'bg-emerald-500', sort_order: 100, description: '{"icon": "RefreshCw", "category": "SYSTEM"}' },
    { type: 'ATTENDANCE_RULE_KEY', key: 'ABSENT_REFUND', label: 'คืนค่า HP (แก้ขาดงาน)', color: 'bg-blue-500', sort_order: 101, description: '{"icon": "RefreshCw", "category": "SYSTEM"}' },
    { type: 'ATTENDANCE_RULE_KEY', key: 'FORGOT_CHECKOUT', label: 'ลืมตอกบัตรออก (Penalty)', color: 'bg-rose-500', sort_order: 102, description: '{"icon": "AlertTriangle", "category": "SYSTEM"}' },
    { type: 'PLATFORM_CONFIG', key: 'YOUTUBE', label: 'YouTube Studio', color: 'bg-red-50 text-red-600', sort_order: 1, description: 'https://studio.youtube.com/channel/UC/videos/upload?d=ud' },
    { type: 'PLATFORM_CONFIG', key: 'FACEBOOK', label: 'Facebook Reels', color: 'bg-blue-50 text-blue-600', sort_order: 2, description: 'https://www.facebook.com/reels/create' },
    { type: 'PLATFORM_CONFIG', key: 'TIKTOK', label: 'TikTok Upload', color: 'bg-zinc-50 text-zinc-600', sort_order: 3, description: 'https://www.tiktok.com/upload' },
    { type: 'PLATFORM_CONFIG', key: 'INSTAGRAM', label: 'Instagram Create', color: 'bg-pink-50 text-pink-600', sort_order: 4, description: 'https://www.instagram.com/reels/create/' },
];
